### ISSUE TITLE
reference solver

### ISSUE THREAD

**Issue by antham** [src-d/go-git#137]
Hello,

I wrote a feature here : https://github.com/antham/gommit/blob/master/reference/reference_scanner.go to be able to solve this kind of reference ```HEAD~2^^```, I was wondering if it could be interesting for your project to have that, I could send a PR.

**Comment by mcuadros** [comment]
very cool gommit, great to see that you are using go-git. 

The functionality cover by your ` reference` package is really relevant for go-git. So we will be more than happy to have a PR about this. Great job!

It requires a bit few job, cannot be merged directly because we need to agree the API, the current API should be improved. So if you want we can work on it, if you thing is to much work, we can do a cherry-pick on work on top of your work.  (I prefer the first options)

As a start, can you tell me the documentation you took as reference to implement it? I was ready reading https://www.kernel.org/pub/software/scm/git/docs/gitrevisions.html, looks like is called `Revision`

**Comment by antham** [comment]
Yep I'was wondering about api to use in your project as well. 

I did it based on thing I found around and based only on the fact that I needed to solve ~ and ^, so some elements are missing, naming as you pointed out isn't correct, it's a good opportunity to improve that. About branching name, I followed this post on stackoveflow http://stackoverflow.com/questions/3651860/which-characters-are-illegal-within-a-branch-name.

**Comment by mcuadros** [comment]
Ok, great, your help is highly appreciated.

We can go step by step with the PRs, first you can submit one with the Parser/Tokenizer/etc and the Resolver and after we can see the rev list functionality (aka FetchCommitInterval) because we are devoloping something similar.

My proposal is the following:
- Implement `Revision` entity as `type Revision string`  and not as plain string 
- Change the signature of `FetchCommitByID` to:`ResolveReference(r *git.Repository, rev Revision) (plumbing.Hash, error)`

- Place all the parser, tokenizer, etc in an internal package called `revision` at the root of the package. This package deals with strings, not with the type `Revision`
- Review the parser/tokenizer, to be formal with the """spec""" described here https://www.kernel.org/pub/software/scm/git/docs/gitrevisions.html, (or if you find a better source, this one), if you find something hard and arcane with can put a TODO, is not required implement all the functionality 

What do you thing? Thanks.

**Comment by antham** [comment]
So if I get it right, you want to be able to create a revision and it's when you call ResolveReference against a revision that you obtain the hash tied to the revision. So everything is done in this method by calling stuffs defined in a revision package.

It's fine for me, I will do that.
