### ISSUE TITLE
Duplicate Filesystem Abstraction

### ISSUE THREAD

**Issue by bclermont** [src-d/go-git#155]
Just a suggestion, there is a great library here https://github.com/spf13/afero that implement elegantly a lot of `storage` and `utils/fs`.

You can just use afero fs interface and run from memory, filesystem, and more.

**Comment by mcuadros** [comment]
I know afero from spf13 is a very good implementation, actually this should be part (some day) of the standard library (at least the interface) 

Our implementation is very similar, but for some methods works different, for example `Create` method, creates the folders if needed (since in git the folder not exists). Sound like a waste of time, but we prefer minimize the number of dependencies. 

A PR is more than welcome adding a kind of AferoFS, to allow the users use file systems already written for afero.

Best regards
