### ISSUE TITLE
SSH connection without SSH-agent

### ISSUE THREAD

**Issue by skyflyer** [src-d/go-git#206]
I'm having an issue connecting to git repository over ssh on windows, where I don't have an SSH agent running.

In `ssh/common.go`, the `command.connect` method calls `c.setAuthFromEndpoint()` which in turn tries to connect with SSH agent and fails. The method's comments note:

```
connect connects to the SSH server, unless a AuthMethod was set with
SetAuth method...
```

but for me, that does not work. Here is a brief program that reproduces this issue:

```go
func main() {
	repoURL := "ssh://git@hostname:portnum/testing.git"
	signer := getSSHSigner()
	r := git.NewMemoryRepository()
	err := r.Clone(&git.CloneOptions{
		URL:  repoURL,
		Auth: &gitssh.PublicKeys{User: "git", Signer: signer},
	})
	check(err)
}
```

The error returned is `dial unix: missing address`, which is correct (in a way), since there is no SSH agent environment variable available, so there's nowhere to connect to. The `getSigner` function above retrieves the ssh.Signer from a private key, supplied to the program.

I can prepare a pull request with a fix, if you'd like that; it seems to me, that we would need to reorganise some code, as currently, `Auth` does not get propagated down to the actual transport layer.

**Comment by mikkeloscar** [comment]
I have the same problem as @skyflyer (on linux where I don't want to use the ssh-agent but pass in a privatekey).

**Comment by mcuadros** [comment]
Exactly the `CloneOptions.Auth` field is totally unused, the only viable method to provide an auth config right now is using the endpoint and this is not enough or valid. We will find a solution in the next days.

**Comment by amlweems** [comment]
I've been trying to find a way to implement this and it seems tricky without changing the interfaces significantly.

The general flow for `transport/http` interface is: create the session using `NewFetchPackSession` (which basically initializes a struct with an http.Client), optionally call `session.SetAuth(auth)` if needed, and call `FetchPack()` to execute the actual network connections.

The above flow works great because the initialization doesn't perform any network activity and it follows the `Session` interface in `transport/common.go`. The general flow for the `transport/ssh` interface is: create the session and Dial the SSH server using SSH agent for authentication and call `FetchPack()` to read from stdin/stdout.

I think the SSH transport needs to be broken out so that network connectivity happens during `FetchPack()` instead of in the session init, however, this is a rather large modification to the architecture.

I'm keen to get this issue fixed (I've got a temporary hack locally because I need SSH keys). Happy to help with discussion / design / code if possible.

**Comment by smola** [comment]
This is fixed now, thanks to @amlweems!

**Comment by Wintermute1** [comment]
hey guys, is it possible to use deploy-key only for verification? I don't want to use ssh-agent.

```
signer, err := ssh.ParsePrivateKey([]byte(sshKey))
	auth := &sshGit.PublicKeys{User: "git", Signer: signer}
	_, err = git.PlainClone(Destination, false, &git.CloneOptions{URL: repo, Auth: auth})
	if err != nil {
		log.Printf("unable to clone repo %v", err)
	}
```
