### ISSUE TITLE
Can't PlainClone a Local Repository

### ISSUE THREAD

**Issue by zachgersh** [src-d/go-git#396]
Hey All,

During testing I am creating local repositories on my filesystem and wanting to treat them as "remote".

I've tried both types of what I believe should be valid URLs

`file://var/folders/zg/7727fl_x1n906p44h9b5mtxh0000gn/T/git-repo310648135`
AND
`/var/folders/zg/7727fl_x1n906p44h9b5mtxh0000gn/T/git-repo310648135`

When calling `Head()` I basically end up getting.

```
reference not found
```

Listing References on the repo does give me back `HEAD`. Am I doing something incorrectly here?

**Comment by zachgersh** [comment]
Seems like it had to be:

```file:///``` instead of ```file://```

Seems like either should work? Also error was misleading but switched to `repository not found`

**Comment by smola** [comment]
@zachgersh This is how standard URL works: `file://` is the scheme part, the third `/` is the first slash of an absolute UNIX path. `file://var/folders/zg/7727fl_x1n906p44h9b5mtxh0000gn/T/git-repo310648135` actually means `var/folders/zg/7727fl_x1n906p44h9b5mtxh0000gn/T/git-repo310648135` relative to your current path. Note that this is by design.

We could definitely improve the error, but that will have to wait until a pending major overhaul of error handling in go-git probably based on https://github.com/src-d/go-errors but that will probably not happen in the short term.
