### ISSUE TITLE
Reverse repo.References()?

### ISSUE THREAD

**Issue by caarlos0** [src-d/go-git#488]
I need to walk the references in a reverse order (newer to older). Didn't find a way of doing that until now.

I ended up getting all the refs and reversing the slice, something like:

```go
var refs []*plumbing.Reference
iter, _ := repo.References()
iter.ForEach(func(ref *plumbing.Reference) error {
	refs = append(refs, ref)
	return nil
})
sort.Slice(refs, func(i, j int) bool {
	return i > j
})
 for _, ref := range refs {
	// blah
}
```

this doesn't seem efficient, as I'm holding all refs in a slice. Is there a better way of doing that?

FWIW, I'm doing that to get the latest 2 tags (https://github.com/goreleaser/goreleaser/pull/311), with the  `git` + `exec.Command` impl I was doing a `git describe` for that.

Thanks for the great lib BTW 🍻

**Comment by mcuadros** [comment]
The references are not iterated in a deterministic way, is dependent of the storage, in filesystem depends of the order in the file and in memory are in a [map](https://github.com/src-d/go-git/blob/master/storage/memory/storage.go#L195)

Also I am not sure if upload-pack is serving the references in any particular order. 

If you are working only we annotated tags (because you are using GitHub releases(, you can sort it by the date from the `Tag` object.

**Comment by caarlos0** [comment]
Hi @mcuadros , I can't assume that the tags are annotated :/

Any ETA for the `describe` compatibility?

**Comment by mcuadros** [comment]
If the are not annotated you can use the date of the commit pointed. 
This works? We don't have any ETA, but we are open for PRs

**Comment by mcuadros** [comment]
reopen if need it.
