### ISSUE TITLE
Repository directory path

### ISSUE THREAD

**Issue by calvn** [src-d/go-git#559]
Is there as way to get the path of the repository was cloned or opened with `PlainOpen` or `PlainClone`? There does seem to have a public field or method that can retrieve that.

**Comment by calvn** [comment]
I realize that this is outside the context of the repository object itself, just like how the .git directory does not contain this information so feel free to close.

**Comment by orirawlings** [comment]
Hey @calvn,

Some `*Repository` instances are not backed by file storage, so there isn't any explicit convenience in the API for this. If you can assume that the repository was created with `PlainOpen` or `PlainClone` we can rely on some type coercions to obtain the data you're looking for. Because this is based on type coercions, there is no guarantee this code would continue to work if underlying implementation details of the `gopkg.in/src-d/go-git.v4` or `gopkg.in/src-d/go-billy.v3` libraries were to change.

```
package main

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/src-d/go-billy.v3/helper/chroot"
	"gopkg.in/src-d/go-git.v4"
	. "gopkg.in/src-d/go-git.v4/_examples"
	"gopkg.in/src-d/go-git.v4/storage/filesystem"
)

// Open an existing repository in a specific folder.
func main() {
	CheckArgs("<path>")
	path := os.Args[1]

	// We instance a new repository targeting the given path (the .git folder)
	r, err := git.PlainOpen(path)
	CheckIfError(err)

	p, err := root(r)
	CheckIfError(err)

	// Clean up the path
	if !filepath.IsAbs(p) {
		pwd, err := os.Getwd()
		CheckIfError(err)
		p = filepath.Join(pwd, p)
	}

	fmt.Println(filepath.Clean(p))
}

func root(r *git.Repository) (string, error) {
	// Try to grab the repository Storer
	s, ok := r.Storer.(*filesystem.Storage)
	if !ok {
		return "", errors.New("Repository storage is not filesystem.Storage")
	}

	// Try to get the underlying billy.Filesystem
	fs, ok := s.Filesystem().(*chroot.ChrootHelper)
	if !ok {
		return "", errors.New("Filesystem is not chroot.ChrootHelper")
	}

	return fs.Root(), nil
}
```
