### ISSUE TITLE
Parsing history of repo

### ISSUE THREAD

**Issue by megamx28** [src-d/go-git#566]
I'm trying to find a way to parse the history of the repo to insert it into our database to run some reports.  This includes all merges, commits, branches, etc.. (full replay similar to git clone --mirror).

I'm struggling to find if I can get this parsable output from go-git.  If you could point me in the right direction, much appreciated

**Comment by orirawlings** [comment]
Hey @megamx28,

The [`Repository`](https://godoc.org/gopkg.in/src-d/go-git.v4#Repository) type provides a handful of methods for iterating over objects of a particular type which are stored in the repository. The objects returned from the iterators are object-oriented representations of the parsed git data. You could, for instance, extract the various fields you care about for insertion into a database, or for building a report directly.

* [`(*Repository).References`](https://godoc.org/gopkg.in/src-d/go-git.v4#Repository.References) - Provides an iterator over each reference in the repository (i.e. each branch and tag name stored in the repository)
* [`(*Repository).CommitObjects`](https://godoc.org/gopkg.in/src-d/go-git.v4#Repository.CommitObjects) - Provides an iterator over each commit object in the repository store (in no particular order)
* [`(*Repository).BlobObjects`](https://godoc.org/gopkg.in/src-d/go-git.v4#Repository.BlobObjects) - Provides an iterator over each blob (i.e. contents of a tracked file) present in the repository store
* [`(*Repository).TreeObjects`](https://godoc.org/gopkg.in/src-d/go-git.v4#Repository.TreeObjects) - Provides an iterator over each tree (i.e. directory tracked in git) present in the repository store
* [`(*Repository).TagObjects`](https://godoc.org/gopkg.in/src-d/go-git.v4#Repository.TagObjects) - Provides an iterator over each annotated tag object present in the repository store

Alternatively you are free to iterate over all types of objects at once with [`(*Repository).Objects`](https://godoc.org/gopkg.in/src-d/go-git.v4#Repository.Objects), but you'll have to convert each Object returned by the iterator yourself to inspect the details of the Object. (Note: this iterator will not cover any of the References though, so you'll still need to iterate those separately).

Depending on what kind of analysis/reporting you are trying to do, it might be easier to interact with the repository store directly using a library like this one, rather than trying to first replicate all the data into another database before analysis (git is already a database of its own).

If you're really ambitious you could implement your own backing storage implementation for go-git which persists the data into your database of interest and then use the standard fetch or clone operations to initiate replication.
