### ISSUE TITLE
Checking out over https fails

### ISSUE THREAD

**Issue by dsvensson** [src-d/go-git#623]
When trying to checkout `https://gopkg.in/yaml.v2`

I get the following error message:
`pkt-line 3: invalid capabilities: arguments not allowed (symref=HEAD:refs/heads/v2 multi_ack thin-pack side-band side-band-64k ofs-delta shallow deepen-since deepen-not deepen-relative no-progress include-tag multi_ack_detailed no-done oldref=HEAD:refs/heads/v2 agent=git/github-g09a9ed6d3a)`

The following code is used:

    storer := memory.NewStorage()
    repo, err := git.Clone(storer, nil, &git.CloneOptions{URL: "https://gopkg.in/yaml.v2"})
    if err != nil {
        fmt.Println(err)
    }

**Comment by orirawlings** [comment]
I suspect this is due to a bug in the validation code for capabilities (see [(*capability.List).validate](../tree/v4/plumbing/protocol/packp/capability/list.go#L124)). Basically if an capability option isn't recognized, the code automatically assumes that it shouldn't allow arguments. I think in this case, go-git isn't familiar with the `oldref` option, and produces and error on the unexpected argument.

I'll work on a patch.
