### ISSUE TITLE
RemoveReference doesn't always work

### ISSUE THREAD

**Issue by jfontan** [src-d/go-git#648]
Sometimes deleting several references in a row do not work. In the test file provided several references are deleted a row. When the test finishes the repository sometimes still have references. Adding a sleep between `RemoveReference` calls fixes the problem so it may be caused by a race condition.

https://gist.github.com/jfontan/79187ee5e278f3a769a6a69bfc60a837

**Comment by mcuadros** [comment]
The error was intruduced by @erizocosmico at PR #563 (https://github.com/src-d/go-git/pull/563/commits/5a7b7af0f793b1c25e9543e8511b767f3b739d67#diff-c206d8d5faa79122f47e8d63a810f54aR304)

Since the modifications are done at exactly the same second, even maybe the same nanosecond the modTime remains the same and cache is not refreshed. Even if we modify the code to invalidate the cache this doesn't means that an external program can reproduce a similar behavior.

@erizocosmico the read of references are a bottleneck? How much was improvement of this PR?

//cc @orirawlings

**Comment by erizocosmico** [comment]
The main bottleneck was traversing all directories under `refs/` (because `Refs` was being called inside `Ref`) as far as I remember, so I think we should be good reverting that. We could maybe just read until the reference is found, not making it necessary to read the whole file, for example.
