### ISSUE TITLE
Checkout problem

### ISSUE THREAD

**Issue by supermock** [src-d/go-git#692]
I'm using **gitlab.com**

My code is like this, I'll simplify it a bit by just putting the instructions in the order I executed:
```go
repository, err = git.PlainOpen(repositoryPath)

err = repository.Fetch(&git.FetchOptions{
	Auth:     authSSH,
	Progress: os.Stdout,
	Tags:     git.AllTags,
})

tags, err := repository.Tags()
defer tags.Close()
var reference *plumbing.Reference
tags.ForEach(func(r *plumbing.Reference) error {
	if r.Name().IsTag() && r.Name().Short() == "v0.0.1" {
		reference = r
	}
	return nil
})

worktree, err := repository.Worktree()

err = worktree.Checkout(&git.CheckoutOptions{
	Hash: reference.Hash(),
})
//Well in the execution of Checkout(), it gives me the following error: object not found
```
Do you have any idea why this is happening? (I gave a debugged and find which method throws the error, it's the EncodedObject() method inside the **commit.go** file)

**Comment by orirawlings** [comment]
Hey @supermock, 

Do you know if `v0.0.1` is an annotated tag? If it is, this might be the cause of the failed checkout, because `reference.Hash()` might refer to a tag object instead of a commit object. If so, you'd need to dereference the commit hash that the tag refers to first before passing to `Checkout`.

I think the `Checkout` method can already do this all for you though. Instead of looking up the tag hash yourself, try this:

```
repository, err = git.PlainOpen(repositoryPath)

err = repository.Fetch(&git.FetchOptions{
	Auth:     authSSH,
	Progress: os.Stdout,
	Tags:     git.AllTags,
})

worktree, err := repository.Worktree()

err = worktree.Checkout(&git.CheckoutOptions{
	Branch: plumbing.ReferenceName("refs/tags/v0.0.1"),
})
```

**Comment by supermock** [comment]
Thank you!
