### ISSUE TITLE
Get detached-HEAD info

### ISSUE THREAD

**Issue by maja42** [src-d/go-git#707]
When checking out a remote branch inside a git-repository (where no related local branch exists), I get the following information with standard git:

```
$ git checkout origin/develop
...
You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.
...

$ git branch
* (HEAD detached at origin/develop)
  develop
  master
```
When opening the repository with go-git, I want to get the same information: `HEAD detached at origin/develop`.

I can retrieve the current branch by using `repo.Head()` and I can detect the detached-HEAD state via `isDetachedHead := repo.Head().Name() == "HEAD"`

Is there a way to find out which exact remote branch is currently checked out? In my example, this would be "origin/develop".

**Comment by orirawlings** [comment]
Hey @maja42,

[`(*git.Repository).Head()`](https://godoc.org/gopkg.in/src-d/go-git.v4#Repository.Head) will resolve the `HEAD` reference if it is currently a symbolic ref (i.e. not detached). This indeed causes the `repo.Head().Name()` to be the name of the target reference rather than `"HEAD"`, so it should be a suitable way to detect detached HEAD state. Allow, I do recommend using the constant `plumbing.HEAD` rather than the literal `"HEAD"` in your comparison.

When in detached HEAD state, `HEAD` points directly to a commit hash. There can, of course, be multiple other references which point to the same hash. This complicates the answer to your question.

To print out all other references which point to the same hash as `HEAD` you could use code like the following:
```
package main

import (
	"fmt"
	"os"

	"gopkg.in/src-d/go-git.v4"
	. "gopkg.in/src-d/go-git.v4/_examples"
	"gopkg.in/src-d/go-git.v4/plumbing"
)

func main() {
	CheckArgs("<path>")
	path := os.Args[1]

	r, err := git.PlainOpen(path)
	CheckIfError(err)

	head, err := r.Head()
	CheckIfError(err)

	// Iterate over all references in the repository to see which point to the same commit as HEAD
	refs, err := r.Storer.IterReferences()
	CheckIfError(err)
	err = refs.ForEach(func(ref *plumbing.Reference) error {
		if ref.Hash() == head.Hash() {
			fmt.Println(ref)
		}
		return nil
	})
	CheckIfError(err)
}
```

This still doesn't pinpoint which reference was used in the `git checkout` initiating the detached HEAD state.

It appears that `git branch` uses information from the reflog for `HEAD` (`.git/logs/HEAD`) in order to piece back together which reference was used during `git checkout`. Unfortunately, at this time `go-git` doesn't provide any APIs for interacting with the reflog data in a git repository, so you wouldn't be able to narrow down further than the code I posted above.

We certainly welcome contributions which introduce support for reflog data.


Cheers
