### ISSUE TITLE
Create Branch?

### ISSUE THREAD

**Issue by thobens** [src-d/go-git#713]
First off, there seems to be a discrepancy between https://github.com/src-d/go-git/tree/v4.0.0 and https://gopkg.in/src-d/go-git.v4. At least the file `options.go` is different, the one on gopkg.in is missing the `CheckoutOptions.Create` field.

This brings me to the question: How can one create a branch without this option?
 
I use this code to checkout a branch and create it if it does not exist
```
func createBranch(repo *git.Repository, branchName string) error {
	wt, err := repo.Worktree()
	if err != nil {
		return err
	}

	head, err := repo.Head()
	if err != nil {
		return err
	}

	var ref plumbing.ReferenceName
	ref = (plumbing.ReferenceName)("refs/heads/" + branchName)

	err = wt.Checkout(&git.CheckoutOptions{
		Branch: ref,
		Hash:   head.Hash(),
		// Create: true, <-- not available
	})

	return err
}
```

**Comment by mcuadros** [comment]
Can you check if `Create` is still missing, the v4.0.0 was release and should contain this. 

In order to create and remore references, idenepent of the `Worktree` you should do this using the [`storer.ReferenceStorer`](https://godoc.org/gopkg.in/src-d/go-git.v4/plumbing/storer#ReferenceStorer).

Please take a look to the `branch` example: https://github.com/src-d/go-git/blob/master/_examples/branch/main.go

**Comment by thobens** [comment]
Using the `ReferenceStorer` works. I checked the latest v4 release and can confirm that the `Create` option is now there. Thanks!
