### ISSUE TITLE
storage: filesystem, support of git-config file, read/write

### ISSUE THREAD

**Issue by mcuadros** [src-d/go-git#81]
Now the support is implemented https://godoc.org/gopkg.in/gcfg.v1, but this library only support decode of a INI file into a struct. 

Give support to read and write remote (not is required fully support, since no other features from the config are being use by go-git) but the other flags in the original file should remain untouched.

**Comment by mcuadros** [comment]
@ferhatelmas you are more than welcome on contribute here

**Comment by ferhatelmas** [comment]
@mcuadros I checked here and I have some questions before going fully implementation.

* Do we want to use another package for writing INI file ? Or, should we handle ourselves since updated keys are small part of the file ?
* If so, what is your selection? Options:
   - [go-ini/ini](https://github.com/go-ini/ini)
   - [Unkwon/goconfig](https://github.com/Unknwon/goconfig)
   - others that I'm not aware of.
* What is the use-case for writing ? Do we want only to append remotes to file or override subsections while keeping rest as it is ?

**Comment by smola** [comment]
@ferhatelmas I'll be working on this soon (probably tomorrow). If you want to start with it now, you can do the reader. We prefer doing it from scratch so we can deal with the particularities of git's config format. In our use case, we want to deserialize the whole config and be able to write it again. We should support deserializing/serializing arbitrary sections/options that are unknown to us.

**Comment by ferhatelmas** [comment]
@smola I'm travelling for a [conference](https://reactiveconf.com/) so I won't be able to do much on weekdays. Please, you give a head start and I will chime in. Also, if we want to do it from scratch, why not implement in a separate package and use here ?

**Comment by smola** [comment]
@ferhatelmas Super-short-term: I will be doing a quick and dirty writer for our use case (it won't preserve comments, for example). The reader will use gcfg (https://godoc.org/gopkg.in/gcfg.v1) which works ok for us but it's not 100% compatible with git.

What we'll want eventually is our own encoder/decoder (in `formats/config`) that is 100% compatible with git, preserves comments when decoding/encoding, etc. You can start this effort, and whenever it's done, we can replace the current implementation with it.
