### ISSUE TITLE
Get the first commit ever

### ISSUE THREAD

**Issue by Mirio** [src-d/go-git#841]
Hi, 
What is the best way (performance like) to get first commit ?
I tried to find a "commit slice" (not iter) but didn't find anything.
Thanks

**Comment by smola** [comment]
@Mirio First you need to think about what is the first commit. There might be more than one "first commit" in a repository, since you can merge two initially different repositories into a single one. For example, the official git repositories has seven "first_commits".

Now, assuming that you just want to get all of them, you just have to iterate over all commits and get those that have no parents. You can do this by getting the `Commit` you want to start walking (for example, the one being pointed by `HEAD`) and then use `object.NewCommitPreorderIter` or one of the other commit iteration functions to get a `CommitIter`.

You'll have to walk them all, and whenever you see a commit with 0 parents, that's the first one, which might be not unique.
