### ISSUE TITLE
Passwords in URL fail on certain characters

### ISSUE THREAD

**Issue by scooterhanson** [src-d/go-git#957]
Using password auth, I noticed that a clone would fail with a password containing `#`.  Wherever the failure is, it truncated the URL from `https://myuser:xyz#123@abc.com/...` to `https://myuser/...`.  The resulting message from this says `Failed to clone repository: Get https://myuser/info/refs?service=git-upload-pack: dial tcp: lookup myuser: no such host`.

This happens before anything ever gets to `PathEscape()` in plumbing/transport/common.go.  There are other failures with varying messages that happen if the password contains `%`, `/`, and `^`.  Because `%` gives an error, I can't pass in a pre-escaped string.

**Comment by smola** [comment]
@scooterhanson Are you specifying user and password with `BasicAuth` or are you adding it to the endpoint URL directly? If it is the later case, you should escape the `#` character, which is just not valid in that case.

**Comment by smola** [comment]
Using escaped user and passwords in URLs seems to work correctly: https://github.com/src-d/go-git/pull/968

I'm closing the issue, since it is expected that using an unescaped `#` in a password directly in the URL has this behavior. Feel free to post more details if I closed this incorrectly. Thanks.
